

const teamData = [
     {
      position: 'President',
      name: 'Anusha Mahajan',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1718996384/Anusha_president-06-17_at_23.18.32_17e91d6d_p6orea.jpg',
      email: '',
      instagram: 'https://www.instagram.com/anushaaaa.___',
      phone: '9873848895',
      branch: 'MAE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/anushamahajan',
      twitter: '',
    },
    {
      position: 'President',
      name: 'Samyah Khan',
      image: ' https://res.cloudinary.com/dptfs4ixa/image/upload/v1719066517/WhatsApp_Image_2024-06-22_at_18.24.50_c5925882_lgvxti.jpg',
      email: 'samyahkhan15@gmail.com',
      instagram: 'https://www.instagram.com/samyahkhan_/',
      phone: '7042157846',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/samyah-khan-577474253',
      twitter: '',
    },
    {
      position: 'Secretary',
      name: 'Priya Gupta',
      image: '',
      email: '',
      instagram: 'https://www.instagram.com/priya.gupta20044',
      phone: '8595712096',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/priyagupta20044',
      twitter: '',
    },
    {
      position: 'Treasurer',
      name: 'Diya Singla',
      image:'https://res.cloudinary.com/dptfs4ixa/image/upload/v1718996698/Diya_2024-06-17_at_20.33.08_aa29696a_ztkrbz.jpg',
      email: 'diya036btcsai21@igdtuw.ac.in',
      instagram: 'https://instagram.com/diya__singla',
      phone: '8929401833',
      branch: 'CSEAI',
      year: '4',
      linkedin: 'https://www.linkedin.com/in/diya-singla-51905b212 ',
      twitter: 'https://twitter.com/DiyaSingla15?t=Frl7Q-NeZwvRmhguPEBRDw&s=09',
    },  
    
    {
      position: 'Media Lead',
      name: 'Navya Raj',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1719067052/navya-min_tq5bzr.png',
      email: '',
      instagram: 'https://www.instagram.com/navyaraj03',
      phone: '9311840911',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/navya-raj-7bb946261',
      twitter: '',
    },
    {
      position: 'Content lead',
      name: 'Tavleen Kaur',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1718998076/TavleenKaur.jpeg_ivnzcb.jpg',
      email: '',
      instagram: 'https://www.instagram.com/tavleen_45',
      phone: '',
      branch: 'ECE-AI',
      year: '2',
      linkedin: 'https://www.linkedin.com/in/',
      twitter: '',
    },
    {
      position: 'EM lead',
      name: 'Palak Bakshi',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1718998297/Palak-06-17_at_19.07.58_9f413abd_mekhpx.jpg',
      email: '',
      instagram: 'https://www.instagram.com/pbakshi04',
      phone: '',
      branch: 'CSE',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/',
      twitter: '',
    },
    {
      position: 'WebD Lead',
      name: 'Chhavi Verma',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1719052826/chhavi_iiiskc.jpg',
      email: '',
      instagram: 'https://www.instagram.com/v.oletcv/',
      phone: '7303526753',
      branch: 'AIML',
      year: '3',
      linkedin: 'https://www.linkedin.com/in/chhavi-verma-violetcv',
      twitter: '',
    },


    {
      position: 'PR lead',
      name: 'Saloni Singh',
      image: 'https://res.cloudinary.com/dptfs4ixa/image/upload/v1718997529/Saloni_14_Jun_2024_11-52_pm_indqfp.jpg',
      email: '',
      instagram: '',
      phone: '',
      branch: '',
      year: '',
      linkedin: 'https://www.linkedin.com/in/saloni-singh-15963b255',
      twitter: '',
    },

    // {
    //   position: 'temp',
    //   name: 'Megha Agarwal',
    //   image: '/images/Megha_Aggarwal.jpeg',
    //   email: 'megha081bteceai21@igdtuw.ac.in',
    //   instagram: '',
    //   phone: '9818472407',
    //   branch: 'ECEAI',
    //   year: '2',
    //   linkedin: 'www.linkedin.com/in/megha-agarwal-13150222b',
    //   twitter: '',
    // },
   
  ];
  
  export default teamData;
  
